### ISSUE TITLE
Workflow run hangs

### ISSUE THREAD

**Issue by MaxEtMoritz** [MaxEtMoritz/openMensaMax#7]
see https://github.com/MaxEtMoritz/openMensaMax/actions/runs/7441921396/attempts/1.

### TODO:
- [X] Find out on which canteen / Server the workflow hangs --> Dr. Theo Schöller Mittelschule (FO111 dts), mensadigital.de
- [X] Find out why it happens --> the FO111 project has database issues on MensaMax's end: ![grafik](https://github.com/MaxEtMoritz/openMensaMax/assets/71436559/5e395556-e149-4bef-8710-2e7f623fe77b)
- [X] Fix the underlying issue, cancelling the hanging canteen(s) if necessary. --> Fixed by https://github.com/MaxEtMoritz/mensamax-api/commit/7ce3f76f79118dad21818aadf64a4cb1d9de0bf7

**Comment by MaxEtMoritz** [comment]
Note: The FO111 project moved from mensadigital.de to mensaaktiv.de. this is causing the DB issues reported by MensaMax. Seems like FO111 is only half deleted on mensadigital.de.
